In [1]:
%mamba install pandas numpy scikit-learn

mambajs 0.19.13

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas, scikit-learn
Channels: emscripten-forge, conda-forge

Solving environment...
Solving took 3.8953999999999067 seconds
  Name                          Version                       Build                         Channel                       
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
+ brotli-python                 1.2.0                         py313h33caa6c_0               emscripten-forge              
+ certifi                       2026.4.22                     pyhd8ed1ab_0                  conda-forge                   
+ charset-normalizer            3.4.7                         pyhd8ed1ab_0                  conda-forge                   
+ idna                          3.13                          pyhcf101f3_0                  conda-forge                   
+ joblib                        1.5.3

## One Hot Encoding
Using both pandas `get_dummies` and sklearn `OneHotEncoder` on the cars dataset.

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [3]:
df = pd.read_csv('cars.csv')
print(df.sample(5))
print(df.shape)
print("======Unique values in each column======")
print(df.nunique())

        brand  km_driven    fuel         owner  selling_price
7001   Maruti      80000  Petrol  Second Owner         185000
4442  Hyundai      60898  Petrol   First Owner          95000
1838     Tata     120000  Diesel   First Owner         210000
8076   Maruti      50000  Petrol   Third Owner         150000
5771  Hyundai      80000  Petrol   First Owner         250000
(8128, 5)
======Unique values in each column======
brand             32
km_driven        921
fuel               4
owner              5
selling_price    677
dtype: int64


In [4]:
# Using pandas get_dummies — encode fuel and owner
ohe_encoded = pd.get_dummies(df, columns=['fuel', 'owner'])
print(ohe_encoded.columns)

Index(['brand', 'km_driven', 'selling_price', 'fuel_CNG', 'fuel_Diesel',
       'fuel_LPG', 'fuel_Petrol', 'owner_First Owner',
       'owner_Fourth & Above Owner', 'owner_Second Owner',
       'owner_Test Drive Car', 'owner_Third Owner'],
      dtype='str')


In [5]:
# Drop first column to handle multicollinearity
ohe_encoded1 = pd.get_dummies(df, columns=['fuel', 'owner'], drop_first=True)
print(ohe_encoded1.columns)
print(ohe_encoded1)

Index(['brand', 'km_driven', 'selling_price', 'fuel_Diesel', 'fuel_LPG',
       'fuel_Petrol', 'owner_Fourth & Above Owner', 'owner_Second Owner',
       'owner_Test Drive Car', 'owner_Third Owner'],
      dtype='str')
        brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0      Maruti     145500         450000         True     False        False   
1       Skoda     120000         370000         True     False        False   
2       Honda     140000         158000        False     False         True   
3     Hyundai     127000         225000         True     False        False   
4      Maruti     120000         130000        False     False         True   
...       ...        ...            ...          ...       ...          ...   
8123  Hyundai     110000         320000        False     False         True   
8124  Hyundai     119000         135000         True     False        False   
8125   Maruti     120000         382000         True     False        

In [6]:
# Using sklearn OneHotEncoder (drop first to avoid multicollinearity)
ohe = OneHotEncoder(drop='first')
ohe_encoded2 = ohe.fit_transform(df[['fuel', 'owner']]).toarray()
print(ohe_encoded2)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 1.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [7]:
# Combine with non-encoded columns
overall_data = np.hstack((df[['brand', 'km_driven']].values, ohe_encoded2))
print(overall_data.shape)

(8128, 9)
