# Z-Score Normalization — NumPy
Rescales data so each column has mean=0 and std=1. Sensitive to outliers.

In [1]:
import numpy as np

In [2]:
data = np.array([
    [1,  10,  100],
    [2,  20,  200],
    [3,  30,  300],
    [4,  40,  400],
    [5,  50,  500]
])

In [3]:
def zscore_normalizer(data):
    mean_vals = np.mean(data, axis=0)   # average per column
    std_vals  = np.std(data, axis=0)    # spread per column
    return (data - mean_vals) / std_vals

In [4]:
normalized = zscore_normalizer(data)
print('Z-score Normalized Data:')
print(normalized)

Z-score Normalized Data:
[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
